name: Build Web

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Run analyzer
      run: flutter analyze

    - name: Build Web
      run: flutter build web --release --base-href /awtrix-companion/

    - name: Create ZIP archive
      run: |
        cd build/web
        zip -r ../awtrix-web.zip *

    - name: Upload Web artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: build/awtrix-web.zip

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/awtrix-web.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
